CONTRIBUTING.md, CONTRIBUTORS.md, README.md
Rewrites the readme to be more newcomer friendly, makes mention of the support channel, and creates an unpopulated contributors listing.
=> Cleaner Readme Update

installer/WindowsInstaller.iss
Fixes wrong url
Fixes absolute paths in installer
Fixes duplicate gen.exe entries
Fixes avoid installing debug files
=> Fix installer paths and settings

INSTALL.md
=> Update INSTALL.md to list new dependencies

README.md
=> README: Discord and Matrix link + contributing and install links fixed

INSTALL.md
All in one single line, so it's easy to copy-paste and put into the terminal
=> INSTALL: easily copy-paste Debian/Ubuntu dependencies

.github/PULL_REQUEST_TEMPLATE.md
Closes #157 
I've basically copied [Minetest one](https://github.com/minetest/minetest/blob/master/.github/PULL_REQUEST_TEMPLATE.md), removing the Todo section (as people can use drafts instead)
=> Add PRs template

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> automatic labels when opening an issue

.gitmodules, src/script/duktape/engine.cpp
Updating to Duktape 2.6.0 since it is much faster than 1.4.0 and supports more JS features.
=> Update duktape and point submodule to new repo

src/base/fs_unix.h, src/base/thread.cpp
These commits fix a few issues that I encountered on Linux with musl libc.
=> base: Fix issues with musl libc

.builds/alpine.yml, .builds/arch.yml, .builds/debian.yml
As discussed in #102.
I can help set up integration with sourcehut builds, but I'll likely need access to the repository.
=> Add sourcehut build manifests

CMakeLists.txt, src/CMakeLists.txt, src/app/CMakeLists.txt, src/script/function.h, src/she/CMakeLists.txt
Fixes compilation errors on MacOS+Clang.
=> MacOS support

src/she/sdl2/sdl2_surface.cpp
Now selections won't render with a solid line anymore.
=> Implementation of checked drawing mode for marching ants

CMakeLists.txt, INSTALL.md, src/CMakeLists.txt, src/app/CMakeLists.txt, src/script/CMakeLists.txt
This is the change discussed on issue: [LibreSprite/LibreSprite-proposals#29]
Closes https://github.com/LibreSprite/LibreSprite-proposals/issues/29
=> Bump language version from C++11 to C++14

src/she/sdl2/she.cpp
=> Send a mouseup event after a doubleclick event

src/script/duktape/engine.cpp, src/script/value.h
With this it will become possible to have API functions that return/receive arrays of bytes.
It can be used to efficiently draw multiple pixels at once or for filesystem access.
=> Allow transferring large amounts of data into/from scripts

src/CMakeLists.txt, src/app/script/script_menu.cpp
According to the documentation, this should be all that's needed for scripts to work on Windows.
I haven't actually been able to test this due to not having a Windows machine for development.
=> Enable wholearchive flag

src/she/sdl2/she.cpp
Press period, don't see a crash.
=> Fixes #245 segfault when pressing unrecognized keys

src/she/sdl2/she.cpp
=> Force redraw for entire window in exposed event

.github/workflows/cmake.yml, CMakeLists.txt, INSTALL.md, cmake/FindV8.cmake, src/app/CMakeLists.txt, src/script/CMakeLists.txt, src/script/v8/engine.cpp
closes LibreSprite/LibreSprite-proposals#32
To test, try this script:
```js
let x = 1; // duktape does not support let
console.log("x = " + x);
```
=> Allow running JavaScript using V8 instead of Duktape

src/app/ui/editor/editor.cpp, src/she/sdl2/sdl2_display.cpp, src/she/sdl2/sdl2_surface.cpp
=> Fix sdl2 line bugs

src/app/script/app_scripting.cpp, src/app/ui/devconsole_view.cpp, src/app/ui/devconsole_view.h, src/script/duktape/engine.cpp, src/script/engine.h, src/script/lua/engine.cpp, src/script/v8/engine.cpp
Added a dropdown to the devconsole (F12) so that you can choose which language the input is in.
=> Make devconsole work with multiple scripting engines

data/widgets/paste_text.xml, src/app/commands/cmd_paste_text.cpp, src/app/ui/font_popup.cpp, src/app/ui/skin/skin_theme.cpp, src/ft/face.h, src/she/common/freetype_font.cpp, src/she/common/freetype_font.h, src/she/common/sprite_sheet_font.h, src/she/font.h, src/she/keys.h, src/she/sdl2/she.cpp, src/ui/entry.cpp, src/ui/entry.h, src/ui/widget.cpp, src/ui/widget.h
Closes LibreSprite/LibreSprite-proposals#36
It seems the font library also supports otf files, so I let it load them as well while I was at it.
=> Improve text input

src/app/res/resources_loader.cpp, src/app/task_manager.h
=> Ensure task results are delivered in the correct order

src/she/sdl2/sdl2_display.cpp
=> Fix minimizing window

src/app/modules/gui.cpp, src/she/display.h, src/she/sdl2/sdl2_display.cpp, src/she/sdl2/sdl2_display.h
=> Change the window icon

src/app/script/api/image_script.cpp
Adds a few functions for reading/writing pixels using an array instead of one-by-one.
Example script:
```js
var img = app.activeImage;
var data = img.getImageData();
for (var i = 0; i < data.length;) {
data[i++] = Math.random() * 255;
data[i++] = Math.random() * 255;
data[i++] = Math.random() * 255;
data[i++] = 0xFF;
}
img.putImageData(data);
```
=> Allow reading/writing all of an image's pixels at once

.github/workflows/codeql-analysis.yml
- Goal of the PR: Improve security 
- How does the PR work: scans code for known vulnerabilities
- Does it resolve any reported issue: No
Every pull request is scanned
=> Create code analysis

INSTALL.md
=> Update required MacOS version to 11.0 

.github/workflows/submodules-CD.yml
Fixes #298 
Output on my personal fork: https://github.com/Zughy/LibreSprite/releases/tag/d 
Wait for the next release and see
=> Deliver submodules too on every release

src/app/app.cpp, src/app/app_options.cpp, src/app/commands/cmd_about.cpp, src/app/log.cpp, src/app/send_crash.cpp, src/app/shell.cpp, src/config.h
I've also removed the `v` before the version, as it wasn't that necessary and a bit too "tech savvy"
=> Macro for displaying package and version together

src/app/tools/active_tool.h
=> Include <memory> in active_tool.h

src/app/ui/font_popup.cpp, src/app/ui/skin/skin_theme.cpp, src/app/ui/skin/skin_theme.h, src/base/fs.h, src/base/fs_osx.mm, src/base/fs_unix.h, src/base/fs_win32.h
Reverts LibreSprite/LibreSprite#325
=> Revert "Initial theme support"

data/scripts/examples/http.js, src/app/CMakeLists.txt, src/app/res/http.h, src/app/script/api/storage_script.cpp
Partially implements LibreSprite/LibreSprite-proposals#21
=> Allow scripts to load/store/fetch data

README.md, data/gui.xml
Fixes https://github.com/LibreSprite/LibreSprite-proposals/issues/3
=> Add donation links

README.md
- If not a bug fix, why is this PR needed? What usecases does it solve?
=> update app image link

README.md
Links to the download were broken
=> Fix links to release

src/base/convert_to.cpp, src/base/convert_to.h, src/base/sha1.h, src/base/sha1_rfc3174.h, src/doc/file/pal_file.cpp, src/gfx/region.h
Reverts LibreSprite/LibreSprite#406
=> Revert "fix compile error"

src/render/render.cpp
This PR is a simple fix for issue #413  .
=> render: fixed broken debug assert for image composition

src/CMakeLists.txt, src/app/script/api/image_script.cpp, src/app/ui/skin/skin_theme.cpp, src/app/widget_loader.cpp, src/she/sdl2/she.cpp
Fixes to compile libresprite using MSVC
=> MSVC fixes
