LibreSprite/LibreSprite

desktop/CMakeLists.txt, desktop/aseprite.appdata.xml
Rejected at https://github.com/aseprite/aseprite/pull/1233. You may want to update the URLs when this fork diverges further.
=> Added an appdata.xml file for Linux software gallery integration

INSTALL.md
Replaced some links to the original aseprite repository which would let people clone and compile the non free source.
=> Replaced links to original aseprite in INSTALL.md

README.md
A while back, after I compiled LibreSprite, I turned it into an installer. I have made a reference to the website on the README.md file so Windows users don't have to compile LibreSprite.
=> Small readme update for binaries

.travis.yml
Updates .travis to support AppImage x64 deployment. [Here](https://github.com/PerryHugh/LibreSprite/releases/tag/continuous) is an example, feel free to test.
* AppImages are deployed to the GitHub releases page under the tag "Continuous" when a merge to master takes place. This can be expanded to support feature branch deployment for testing if desired later. The previous "Continuous" tagged release is overwritten.
* Requires a [GITHUB_TOKEN](https://github.com/probonopd/uploadtool/blob/master/README.md) to be added to the official LibreSprite repository.
* MacOS support is seemingly not doable at this time. I tried to get Skia working, but unfortunately the old version's scripts no longer has authentication to Google's servers to download resources, making them fail to build. Building …
=> Travis CI - AppImage Support

README.md
MacOS support is presumed not working. The older version of Skia used doesn't build under the current instructions in [INSTALL.md](https://github.com/LibreSprite/LibreSprite/blob/master/INSTALL.md).
I removed mention of the website, as it currently isn't in a presentable state. I thought it would be better fitting if we add it to the side-bar as most projects do, so it is there now.
=> Add Linux AppImage to README.md, Remove Mention of MacOS For Now.

src/app/resource_finder.cpp, src/app/resource_finder.h
LibreSprite hardcodes the configuration directory to be ~/.config instead of checking for XDG_CONFIG_HOME variable.
Normally these will match up unless if the user decides to change the default value of XDG_CONFIG_HOME or if it's packaged as a flatpak.
=> Add support for XDG Base Directory spec

data/gui.xml
Hello, first PR here. I use ASEprite every day to work and I'm super glad to have found a free software fork :)
Long story short, a few (to me) essential things are missing, so I've decided starting with the most basic one: the "C" shortcut for resizing the canvas. I hope it's fine!
=> Default canvas size shortcut on C

data/gui.xml
One of the things I keep doing by mistake is pressing `Ctrl+J` to duplicate layers and `Ctrl+E` for merging them. This happens because both Krita and Photoshop have the same shortcuts and... well, I think that LibreSprite could follow the same standard. If people don't agree with these shortcuts, please at least let's put some by default because is very annoying not having them.
As `Ctrl+E` was the default shortcut for the spritesheet editor, I've moved this one and the importer onto `Ctrl+Alt+E` and `Ctrl+Alt+I`, as I think these actions are way more sporadic than merging and duplicating layers (I wanted to use `Shift` instead of `Alt` but `Ctrl+Shift+I` is the invert selection shortcut, another standard, so I didn't touch it)
=> Add default shortcuts for layers "Merge down" and "Duplicate" actions

INSTALL.md
Closes #150, as since #102 it wasn't possible to compile on Windows anymore (people needed to manually download all the removed libraries)
I've cleaned up the file a bit and also added a note in the Mac section, warning contributors that right now it doesn't work
=> INSTALL: add instructions to compile with vcpkg on Windows

src/app/script/sprite_wrap.cpp
LibreSprite crashes when you invoke a script on a completely empty cel.
This PR checks if the cel is empty and creates a new one if necessary.
=> Fix crash when trying to use a script on an empty cel

data/gui.xml
`Ctrl+Shift+E` now allows to merge all layers in one (there was no shortcut before). It's a standard shortcut that can be find both on Krita and Photoshop
Not really necessary but... well, just run the program, create more layers and then press `Ctrl+Shift+E`
=> Flatten shortcut

CONTRIBUTING.md
I was browsing old issues and I've discovered there was no plan to support contributing documentation aside from English (https://github.com/LibreSprite/LibreSprite/pull/60). So I've removed the Spanish mention in the contributing file (which was a dead link anyway)
read
=> CONTRIBUTING: remove Spanish missing documentation

src/app/app_menus.cpp
This fixes the compilation error on debug builds caused by the removal of the m_rootMenu variable.
`cmake -DCMAKE_BUILD_TYPE=Debug [...]`
=> Fix compilation error on debug builds

src/app/console.cpp, src/app/script/api/app_script.cpp, src/app/script/api/image_script.cpp, src/app/script/api/layer_script.cpp, src/app/script/api/pixelcolor_script.cpp, src/app/script/api/sprite_script.cpp, src/script/script_object.h
Partial documentation support for the scripting API. Since the API itself is not yet set in stone, this should
not be seen as final. I am sending it as-is so that we can discuss the formatting/style and in hopes that it 
may be of some use since it's better than nothing.
To see the documentation, open an image and run the following script:
`app.documentation()`
It should print everything to the terminal, not to a GUI dialog.
=> Document scripting api

.github/ISSUE_TEMPLATE/code_quality.md
Right now we have bugs here, and features/discussions/meta in the other repo, but a template for code quality reports (like https://github.com/LibreSprite/LibreSprite/pull/208#pullrequestreview-753360921) is missing. This PR adds it. It makes more sense having it here as it's not really a proposal, but more like something to improve the actual code (same as bugs)
=> Add code quality issue template

src/app/ui/palette_listbox.cpp, src/app/ui/palette_listbox.h, src/app/ui/palette_popup.h
PaletteListBox is now purely a UI widget for drawing lists of palettes.
PaletteFileListBox has the functionality of loading palettes from disk.
Closes https://github.com/LibreSprite/LibreSprite-proposals/issues/6
=> Split PaletteListBox into two classes

src/base/safe_ptr.h
Since existing code passes raw pointers around, it is not always possible to know if a pointer to an object is still valid or not.
Generally, the standard solution would be to use shared_ptr together with weak_ptr, but that would involve a large rewrite.
As a workaround, this PR contains a smart pointer (this_ptr) that automatically gets set to nullptr when the initial this_ptr it was copied from is destroyed. 
In short, it gets rid of dangling-pointer problems.
Please see comment in header for further clarification/examples.
=> Implement safe_ptr for safely accessing unowned objects

src/app/commands/cmd_run_script.cpp, src/app/console.cpp, src/app/script/api/console_script.cpp, src/app/script/app_scripting.cpp, src/app/script/app_scripting.h, src/base/injection.h, src/script/duktape/engine.cpp, src/script/engine.h, src/script/function.h, src/script/value.h
This PR does a general clean-up of minor issues with the scripting system. In the process, I've made it possible to send events to scripts and to recycle scripting engine instances so that it doesn't have to setup and tear down the environment multiple times. If a script were to execute each time the mouse moved, for example, you'd need it to be as efficient as possible.
- Allow moving a string into a Value to prevent copying large strings
- Support for vararg API functions such as console.log
- Fix crash when closing app with console open
- Implement vararg support in console.log/assert
- Allow registering injectables with a set of flags
- Allow scripts to listen to events and recycle engine instances
=> General scripting improvements

src/she/sdl2/she.cpp
Files dropped into the app were being ignored.
=> Fix dropfile event

data/gui.xml
As 1.0 is not gonna roll out a stable scripting system, a warn has been added (clicking it doesn't do anything but closing the dropdown menu)
=> Warn about scripts being an experimental feature

src/app/script/api/console_script.cpp, src/app/ui/devconsole_view.cpp, src/app/ui/devconsole_view.h
Language dropdown is no longer a button.
Console.log(...) now shows up in the console instead of a separate pop-up.
=> Further improvements to the devconsole

src/app/CMakeLists.txt, src/app/script/api/palette_script.cpp, src/app/script/api/sprite_script.cpp
Example script:
```js
const pal = app.activeSprite.palette;
for (var i = 0; i < pal.length; ++i)
pal.set(i, Math.random() * 255, Math.random() * 255, Math.random() * 255);
```
=> Allow scripts to alter a sprite's palette

src/she/sdl2/she.cpp
Should fix shortcuts like Ctrl+Shift+E.
=> Prevent unicode text from interfering with shortcut input

src/app/commands/cmd_layer_properties.cpp
Right now the layer properties window can be closed only by pressing enter. This is counter-intuitive
`Shift+P` -> `Esc`
=> Pressing "Esc" closes the layer properties window

CMakeLists.txt
It wasn't possible to compile on 32-bit architectures due to V8 pointers compression, a feature that only works on 64-bit architectures
=> Remove V8 pointers compression on 32-bit architectures

src/ui/manager.cpp
The bug when compiling:
```
/Users/user1/LibreSprite/src/ui/manager.cpp:66:38: error: implicit instantiation of undefined template 'std::array<std::list<ui::Filter>, 22>'
static std::array<Filters, NFILTERS> msg_filters; // Filters for every enqueued message
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
^
```
<br>
Line 66 of `manager.cpp` can't run because it can't find the `array` data-type.
```c
static std::array<Filters, NFILTERS> msg_filters; // Filters for every enqueued message
```
Adding `#include <array>` to the file fixes the bug and allows libresprite to build and run on mac (M1).
=> Fixes bug that prevents compiling on mac.

src/app/resource_finder.cpp
Address https://github.com/LibreSprite/LibreSprite/issues/350
This just allows the app to search for the data folder in /usr/ or /usr/local/ like it would on most *nix systems.
=> data search path for Apple Hardware

src/base/dll_win32.h, src/base/fs_win32.h, src/base/launcher.cpp, src/base/memory_dump_win32.h
Eliminate GCC errors like: `error: cannot convert 'const wchar_t*' to 'LPCSTR' {aka 'const char*'}`
It enforces Wide/Unicode API calls in Windows -- since all versions of Windows NT support it (optimally) and it's extremely unlikely that anyone will compile for Win9x, rendering `TCHAR` cruft completely unnecessary.
Resolves #369 compilation problems (separate linking issues still remain).
Please attempt to compile however compilation has been done previously, especially targeting Windows.  
Specifically, this PR corrects issues when compiling for Windows, with GCC, under ***MSYS2 MinGW UCRT x64***...
```bash
pacman -Syyu
pacman -S cmake …
```
=> Add explicit "wide" Windows API calls & structs

src/base/dll_win32.h, src/base/fs_win32.h, src/base/launcher.cpp, src/base/memory_dump_win32.h
A few days ago I submitted PR #371, which also updated the license & copyright info on each file.  In doing so I (wrongfully) changed the license from MIT to GPL.  This PR will restore the MIT text at the top of those 4 files.
1. This PR Replaces...
```
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
```
2. With...
```
// This file is released under the terms of the MIT license.
// Read LICENSE.txt for more information.
```
No.
1. Ensure license header in `fs_win32.h`, `launcher.cpp`, …
=> Correct license headers

src/base/convert_to.cpp, src/base/convert_to.h, src/base/sha1.h, src/base/sha1_rfc3174.h, src/doc/file/pal_file.cpp, src/gfx/region.h
Fix copilation time error on linux with while comile with clang.
Run copilation on linux with clang.
=> fix compile error

LICENSE.txt
This PR is to inform LibreSprite team that the GPL2 text in LICENSE.txt is different from the current version hosted by FSF at <https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>
If you prefer to only change the address and preserve the existing text (à la [kernel](https://github.com/pombredanne/gpl-history/commit/55ded445e5dc4ad235c1f214bcbe351f9c1d12ab)), let me know and I will alter the PR.
Fixes [rpmlint incorrect-fsf-address](https://fedoraproject.org/wiki/Common_Rpmlint_issues#incorrect-fsf-address)
=> Update GPL2 text

.github/workflows/cmakeMacOs.yml
This aims to address the issue causing the latest MacOS build to fail. See <https://github.com/LibreSprite/LibreSprite/actions/runs/5983905854/job/16234566625>. The URL is incorrect (not pulling the plist from LibreSprite/LibreSprite) so I have pointed it to the right place.
it's github, no idea lol
=> Fix repo URL in MacOS workflow

.github/workflows/cmake.yml, .github/workflows/cmakeAndroid.yml, .github/workflows/cmakeMacOs.yml, .github/workflows/cmakeWin32.yml, .github/workflows/codeql-analysis.yml, .github/workflows/submodules-CD.yml
the github ci trows a warning cause these two actions run on a deprecated version on node; fix it, at least for now
finding all the warning is hard
check the annotations section for the warnings https://github.com/LibreSprite/LibreSprite/actions/runs/7314194370
=> ci: bump checkout & upload-artifacts to v3

src/she/sdl2/sdl2_display.cpp
Without this LibreSprite aborts when compiled with glibcxx asserts.
=> fix out of bounds array access

.github/ISSUE_TEMPLATE/bug_report.md
Adds a couple if checkboxes to the bug report issue template.
Declare using the latest release or build from latest commits.
Declare not using Flatpak (can be removed if the discussion in Discord comes to fruition).
=> Update bug_report.md with Latest version and Flatpak check.

src/base/fs_unix.h
Removes compiler warning and avoids call to std::string constructor with NULL as arg.
Goal of the PR : check return value of `getcwd` to avoid calling `std::string` constructor call when path not found or too long.
Resolves: https://github.com/LibreSprite/LibreSprite/issues/516
Do normal build. `ninja libresprite` step should have 1 less compiler warning when built on *nix systems.
=> Use return value of getcwd

.github/workflows/cmakeLinux.yml, package_linux.sh
- If not a bug fix, why is this PR needed? What usecases does it solve?
This PR aims to adapt the package script to leverage sharun and AppImageTool to make it easier to build modern AppImages. I hope this also makes it easier for the project to distribute aarch64 binaries now as github actions is allowing aarch64 linux runners.
Because this automatically packages everything the app calls during runtime, I have also removed the add function, and let the lib4bin/sharun tools take over for that.
Use my testing build from:
https://github.com/sounddrill31/LibreSprite/releases/tag/13608364921
(x86_64)
Screenshot on my personal OpenSUSE tumbleweed …
=> Build Tooling: Use sharun and AppImageTool to package AppImages

data/gui.xml
Remove duplicate `Alt+C` keyboard shortcut.
Changes default keyboard shortcut to remove frame from `Alt+C` to `Alt+Shift+C`. `Alt+C` conflicted with the window menu's shortcut for the Scripts menu. - I have checked and `Alt+Shift+C` is not assigned in the `gui.xml` file.
#528 
Compile > Open > `Alt+N` - frame added > `Alt+C` - frame removed -- et voila
=> Change duplicate keybind

package_linux.sh
This is not needed and can break libs, it usually breaks hardware acceleration with nvidia users and also causes assertion errors with gtk3. 
See: 
https://github.com/pkgforge-dev/Pixelpulse2-AppImage/pull/5
https://github.com/Rosalie241/RMG/pull/345
Just launch the AppImage, ideally on a distro that is usually incompatible like a musl based one.
=> Remove rpath patch in AppImage
